### ISSUE TITLE
componentの説明について

### ISSUE THREAD

**Issue by hiro0218** [vuejs-miyazaki/vue-hands-on-beginner#1]
## 概要
Vue Componentのtemplateの登録部分は、x-templateを利用する方法で解説する方が分かりやすいのではないか。

## 内容

触りとして、基本例を説明する。

```js
Vue.component('button-counter', {
  data: function () {
    return {
      count: 0
    }
  },
  template: '<button v-on:click="count++">You clicked me {{ count }} times.</button>'
})
```

説明のしやすさ受けての分かりやすさを考えると、X- テンプレートが良さそう？

```html
<script type="text/x-template" id="hello-world-template">
  <p>Hello hello hello</p>
</script>
```

```js
Vue.component('hello-world', {
  template: '#hello-world-template'
})
```

https://jp.vuejs.org/v2/guide/components-edge-cases.html#X-%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88

----

## 対応PR

https://github.com/vuejs-miyazaki/vue-hands-on-beginner/pull/2

**Comment by Oyanagi-Jotaro-Aratana** [comment]
本件対応のプルリクを投げさせていただきました！
