### ISSUE TITLE
devtools について

### ISSUE THREAD

**Issue by Oyanagi-Jotaro-Aratana** [vuejs-miyazaki/vue-hands-on-beginner#4]
拡張詳細で「ファイルの URL へのアクセスを許可する」を ON にしてもらう

**Comment by hiro0218** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/3617124/51724845-964e1080-20a2-11e9-8d7a-6f36f31c24bb.png">

**Comment by mjcreativelab** [comment]
@hiro0218 README の修正、プルリク投げましたのでご確認お願いします！
